#!/usr/bin/env bash
# Ask the MODEL what a materialized config resolves to (#83/#79).
#
#   tests/declare_probe.sh <suite> [extra sed -e args...]
#
# Substitutes the @INPUTS@/@WORK@/@STEM@ tokens in tests/<suite>/config.yaml, runs wtm.x ONCE on it,
# and reports every key the run resolved but the config did not state -- WITH THE VALUE THE MODEL CHOSE.
#
# WHY THIS EXISTS. Two keys (solver.time_integration, solver.time_step.mode) resolve PER METHOD when
# omitted, so filling them in means reproducing a COMBINATION rule. That is precisely what the deleted
# config mirror got wrong. The value must come FROM THE MODEL, never from a second implementation of
# its policy -- so we run it and read full_config.yaml.
#
# One model run, not a suite run: the point is to learn the resolved values before verifying.
set -uo pipefail
cd "$(dirname "$0")"
suite="${1:?usage: declare_probe.sh <suite> [sed -e args]}"; shift
WTM=$(readlink -f ../build/wtm.x)
[ -x "$WTM" ] || { echo "ERROR: no binary at $WTM"; exit 1; }
[ -f "$suite/config.yaml" ] || { echo "ERROR: $suite/config.yaml does not exist yet"; exit 1; }

# Fixtures are generated by the suite, not committed, and a suite may BORROW another suite's
# fixture (fsm_conservation uses fsm_cascade's). Set PROBE_INPUTS to point at the right one.
_src="${PROBE_INPUTS:-$suite/inputs}"
_gen="$(dirname "$_src")"
if [ -f "$_gen/make_inputs.py" ]; then
    ( cd "$_gen" && python3 make_inputs.py >/dev/null 2>&1 ) || true
fi

W=$(mktemp -d /tmp/claude-1000/probe.XXXXXX)
INP=$(readlink -f "$_src" 2>/dev/null || echo "$_src")
sed -e "s|@INPUTS@|$INP|g" -e "s|@WORK@|$W|g" -e "s|@STEM@|probe|g" "$@" "$suite/config.yaml" > "$W/probe.yaml"

if ! "$WTM" "$W/probe.yaml" > "$W/probe.log" 2>&1; then
    echo "== the model REFUSED or FAILED on $suite/config.yaml =="
    # strip the progress bars -- they bury the error in thousands of columns of ANSI
    sed 's/\x1b\[[0-9;]*[A-Za-z]//g' "$W/probe.log" | grep -v "^\[" | grep -vE "^\(|threads\)" | tail -12
    echo "== kept: $W =="; exit 1
fi
echo "== $suite: what the config did not say =="
./config_identity.py --summary "$W" 2>&1
# --report is SILENT when everything is declared, so the summary above is what says "clean".
./config_identity.py --report "$W" 2>&1
echo "== work: $W =="
