#!/usr/bin/env bash
# SERIAL RANK-0 RECHARGE PATH: the branch nothing else in the suite ever executes.
#
# WHY THIS EXISTS. WTM computes the per-step recharge, and splits it by the runoff ratio, in TWO
# places: a distributed loop over each rank's owned cells, and a serial rank-0 loop over the whole
# grid. Which one runs is derived, not chosen:
#
#     distribute_recharge = !fsm_on || !infiltration_on        (WTM.cpp)
#
# so the SERIAL path needs `fsm_on` AND `infiltration_during_flow` together. No test in this suite set
# `infiltration_on 1` -- and no fixture even carried a `vertical_ksat` raster for it to read -- so that
# entire branch, including its own copy of the recharge/runoff split, had never been executed by CI.
# The two copies are duplicated logic guarded only by a code comment saying "Matches the serial loop",
# which is exactly the arrangement that drifts.
#
# WHAT IT ASSERTS
#   1. PRECONDITION  the serial path is really the one taken (the model says so, loudly).
#   2. PRECONDITION  the routed channel is non-zero, so the serial runoff accumulator is exercised
#                    rather than trivially summing zeros.
#   3. MPI-EXACT     every budget column is identical at n=1 and n=4. This is the sharp one: on this
#                    path the runoff accumulator runs on RANK 0 ONLY over the full grid, while every
#                    other rank contributes nothing, and the global total is formed by an Allreduce in
#                    PrintValues. That is correct only because the non-participating ranks contribute
#                    exactly 0 -- an argument that deserves a test rather than a comment.
#   4. CONSISTENT    col 9 == col 19 + col 20 on this path too.
#
#   5. NO DRIFT      the two implementations of the split agree EXACTLY on the input channels
#                    (cols 9/19/20), even though the arms reach very different states -- measured
#                    stored_volume differs by 4x between them, while cols 19 and 20 match to 0.000e+00.
#                    That holds because this fixture's recharge does not depend on the water table
#                    (uniform precip 0.1, evap 0), the same fixture property tests/dt_invariance relies
#                    on for its exactly-invariant input columns. Downstream columns legitimately differ
#                    (the arms differ in infiltration as well as in the loop) and are reported, not
#                    gated -- there is no configuration that gives the DISTRIBUTED path with
#                    infiltration on, so a physics-identical comparison is not available.
#
# Usage:  tests/serial_recharge/run.sh [path/to/wtm.x] [ranks]
set -uo pipefail
cd "$(dirname "$0")"
WTM="${1:-$(readlink -f ../../build/wtm.x)}"
NRANKS="${2:-4}"
[ -x "$WTM" ] || { echo "ERROR: WTM binary not found at $WTM"; exit 1; }

FSMDIR=$(readlink -f ../fsm_consistency)
# The vertical_ksat raster is generated by fsm_consistency/make_inputs.py; regenerate if this fixture
# predates it, since the serial path cannot start without it.
[[ -f "$FSMDIR/inputs/fsm_test_vertical_ksat.tif" ]] || ( cd "$FSMDIR" && python3 make_inputs.py >/dev/null )
INP="$FSMDIR/inputs"
WORK=$(mktemp -d /tmp/serialrech_XXXX); trap 'rm -rf "$WORK"' EXIT
PY="${PY:-python3}"
export OMP_NUM_THREADS=1

mkcfg() { # $1 = stem, $2 = infiltration_on
    ../emit_config.sh > "$WORK/$1.yaml" <<EOF
run_type equilibrium
total_time 10yr
supplied_wt 1
deltat 31536000
report_interval 5
save_nreport_interval 9999
cells_per_degree 10
southern_edge -45
fdepth_a 200
fdepth_b 150
fdepth_fmin 2
infiltration_on $2
fsm_on 1
runoff_ratio 0.3
surfdatadir $INP
region fsm_test
time_start t0
time_end t0
eq_tol 0
textfilename $WORK/$1.txt
outfile_prefix $WORK/${1}_
EOF
}

run() { # $1 = stem, $2 = infiltration_on, $3 = ranks
    local stem="$1" inf="$2" n="$3"
    mkcfg "$stem" "$inf"; rm -f "$WORK/$stem.txt"
    if ! mpirun -n "$n" "$WTM" "$WORK/$stem.yaml" -wtm_anderson -snes_stol 1e-8 \
            > "$WORK/$stem.log" 2>&1; then
        echo "  RUN FAILED: $stem"; grep -iE "what\(\)|ERROR" "$WORK/$stem.log" | head -2 | sed 's/^/        /'
        return 1
    fi
}

echo "=== serial (rank-0) recharge path ==="
echo "WTM binary: $WTM   ranks: 1 vs $NRANKS"
echo
fail=0
run ser_n1 1 1        || fail=1
run ser_nN 1 "$NRANKS" || fail=1
run dist_n1 0 1       || fail=1
[[ $fail -eq 0 ]] || { echo "SERIAL RECHARGE: FAILED (a run did not complete)"; exit 1; }

# 1. PRECONDITION: confirm the branch under test is the branch that ran. The model emits a warning when
#    infiltration forces the serial path; absence of it means this test is silently exercising the
#    distributed loop instead and proving nothing.
if grep -q "serial (rank-0) path" "$WORK/ser_n1.log"; then
    echo "  PASS  PRECONDITION  the SERIAL rank-0 recharge path is the one taken"
else
    echo "  FAIL  PRECONDITION  no serial-path notice in the log -- this run did NOT take the branch"
    fail=1
fi

WORK="$WORK" NRANKS="$NRANKS" "$PY" - <<'PY'
import os, sys
W, N = os.environ["WORK"], os.environ["NRANKS"]
COLS = [(8, "9  total_recharge_added"), (9, "10 total_loss_to_ocean"), (11, "12 total_surface_removed"),
        (12, "13 total_ocean_outflow"), (13, "14 stored_volume"), (17, "18 total_evap_removed"),
        (18, "19 recharge_direct"), (19, "20 runoff_to_surface")]

def last(stem):
    rows = [[float(x) for x in l.split()] for l in open(f"{W}/{stem}.txt")
            if l.split() and l.split()[0].isdigit() and len(l.split()) >= 23]
    return rows[-1] if rows else None

fail = 0
s1, sN, d1 = last("ser_n1"), last("ser_nN"), last("dist_n1")
if s1 is None or sN is None:
    print("  FAIL  missing serial-path output"); sys.exit(1)

# 2. PRECONDITION: the routed channel must actually carry water, or the serial accumulator under test
#    is summing zeros and the MPI check below is vacuous.
ok = s1[19] > 0.0
fail |= not ok
print(f"  {'PASS' if ok else 'FAIL'}  PRECONDITION  routed channel is non-zero on this path "
      f"(col 20 = {s1[19]:.5e})")

# 3. The reduction. Rank 0 holds the whole grid here and every other rank contributes 0.
#
# TWO TOLERANCE CLASSES, measured rather than assumed. The INPUT channels are driven by the forcing and
# come out EXACT (0.000e+00), which is the sharp test of the rank-0-only accumulator. State-derived
# sums carry sub-nanometre floating-point divergence: the final water table itself is NOT bit-identical
# across decompositions here (measured max|dwtd| = 2.824e-10 m, rms 6.936e-11 m -- the active-set
# constraint's known last-bit sensitivity to the decomposition), so sums over it differ by ~1e-10
# relative. Observed worst: col 12 at 1.974e-10 and col 14 at 8.434e-11, so 1e-9 carries ~5x margin.
# These are NOT interchangeable: loosening the INPUT class would discard the only exact check here.
EXACT_COLS = {8, 18, 19}
print(f"\n  n=1 vs n={N}:")
for idx, name in COLS:
    rel = abs(sN[idx] - s1[idx]) / (abs(s1[idx]) or 1.0)
    exact = idx in EXACT_COLS
    tol = 1e-12 if exact else 1e-9
    ok = rel < tol
    fail |= not ok
    print(f"  {'PASS' if ok else 'FAIL'}  {'MPI-EXACT ' if exact else 'MPI-CLOSE '} {name:<26} "
          f"{s1[idx]:>16.9e}  rel diff {rel:.3e}  (tol {tol:.0e})")

# 4. Internal consistency of the two channels on this path.
# The run log prints 12 significant digits (irf.cpp), so this identity is checkable near machine
# precision. At the stream default of 6 it missed by ~5e-7, which is indistinguishable from a real
# accounting error -- the tolerance here should never be loosened to paper that over.
ok = all(abs(r[8] - (r[18] + r[19])) <= 1e-11 * max(1.0, abs(r[8])) for r in (s1, sN))
fail |= not ok
print(f"  {'PASS' if ok else 'FAIL'}  CONSISTENT  col 9 == col 19 + col 20")

# 5. NO DRIFT between the two copies of the split. Gated on the INPUT channels only; see the header.
if d1 is None:
    print("  FAIL  missing distributed-path output"); fail = 1
else:
    print("\n  serial vs distributed recharge/runoff split:")
    for idx, name in [(8, "9  total_recharge_added"), (18, "19 recharge_direct"), (19, "20 runoff_to_surface")]:
        rel = abs(d1[idx] - s1[idx]) / (abs(s1[idx]) or 1.0)
        ok = rel < 1e-11
        fail |= not ok
        print(f"  {'PASS' if ok else 'FAIL'}  NO-DRIFT   {name:<26} serial {s1[idx]:>16.9e}  "
              f"distributed {d1[idx]:>16.9e}  rel {rel:.3e}")
    print("\n  (info) downstream columns -- NOT gated, the arms differ in infiltration too:")
    for idx, name in COLS:
        if idx in (8, 18, 19):
            continue
        rel = abs(d1[idx] - s1[idx]) / (abs(s1[idx]) or 1.0)
        print(f"         {name:<26} serial {s1[idx]:>16.9e}  distributed {d1[idx]:>16.9e}  rel {rel:.3e}")

print("\nSERIAL RECHARGE: " + ("ALL PASSED" if not fail else "FAILED"))
sys.exit(1 if fail else 0)
PY
rc=$?
[[ $fail -eq 0 && $rc -eq 0 ]] || exit 1
